### ISSUE TITLE
host is down. pls fix

### ISSUE THREAD

**Issue by dmweis** [xShteff/SWA-Assignment-2#1]

**Comment by xShteff** [comment]
what. why. fine. I legit got the password first try, but I can't deploy on the same app anymore, it probably expired.
![image](https://user-images.githubusercontent.com/9394141/89720169-b10b8000-d9cf-11ea-8487-8231ad131b5e.png)

**Comment by xShteff** [comment]
What. Why. No.

**Comment by xShteff** [comment]
Wait, did I or did you deploy? I can't remember the password. Also I'm pretty sure I used a VIA account, which is probably dead.

**Comment by dmweis** [comment]
I am pretty sure this was on a student license. And I don't think either one of us will ever be a student again 😄
